### ISSUE TITLE
In the timeline, when we insert weeks for a new year, it displays incorrectly

### ISSUE THREAD

**Issue by danrocha** [TechLabs-Berlin/radar#6]
When adding the week numbers in [phases.yaml](https://github.com/TechLabs-Berlin/radar/blob/master/content/phases.yaml), if the later phases have a week number lower than the earlier phases, the calculation which displays the week number in the timeline becomes negative.

For example, the last phase of the upcoming semester starts on week 51 (1st week of December), and ends 8 weeks later, week 7 (3rd week of February):

```yaml
- title: Projects
  description: |
    This is prime time! You imagine and implement a prototype in a project of your own.

    You team up as a group of 4-6 Techies and work together to create something big. Experienced mentors will be on your side for support.
  startWeekNum: 51
  duration: 8

- title: Closing
  description: |
    You finish up your prototype and submit the final result to us. We organize a closing ceremony where you will be given your Digital Shaper Certificate.
  startWeekNum: 7
  duration: 1
```

However, the timeline then displays a negative number:

<img width="627" alt="Screenshot 2020-09-11 at 08 39 12" src="https://user-images.githubusercontent.com/5139870/92876363-4dc7a000-f40a-11ea-9b4d-1ed0daae23cc.png">

**Comment by danrocha** [comment]
My current solution is to use an incremental week number: 

```yaml
- title: Projects
  description: |
    This is prime time! You imagine and implement a prototype in a project of your own.

    You team up as a group of 4-6 Techies and work together to create something big. Experienced mentors will be on your side for support.
  startWeekNum: 51
  duration: 8

- title: Closing
  description: |
    You finish up your prototype and submit the final result to us. We organize a closing ceremony where you will be given your Digital Shaper Certificate.
  startWeekNum: 59
  duration: 1
```

but this will break the week indicator as the term progresses.
